# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

org: iconify
app: aws-pdf-merge
service: gh-pdf-merge # NOTE: update this with your service name
custom: ${file(./wire-o.yml)}
provider:
  name: aws
  runtime: nodejs12.x
  profile: default
  timeout: 29
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
      Resource: arn:aws:lambda:us-east-1::*:*
    - Effect: Allow
      Action:
        - apigateway:POST
      Resource: arn:aws:apigateway:us-east-1:*:*
    - Effect: Allow
      Action:
        - s3:*
      Resource: "*"
functions:
  index:
    handler: dist/app.handler
    events:
      - http:
          path: merge
          method: POST
          integration: lambda
    environment:
      s3BucketName: ${self:custom.s3BucketName}
resources:
  Resources:
    mergedPDFs:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.s3BucketName}
